#!/usr/bin/env bash
#Transfer file from client to server
FILE_PATH=$1
SERVER_IP=$2
USER_NAME=$3
PRIVATE_KEY_PATH=$4

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file FILE_PATH SERVER_IP USER_NAME PRIVATE_KEY_PATH"
else
	scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY_PATH" "$FILE_PATH" "$USER_NAME@$SERVER_IP":~/
fi
