#!/usr/bin/env bash
# A script that uses while to loop through 1 to 10
# displays messages using depend on if conditions.

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
